### ISSUE TITLE
Looks like New Relic SDK is not supported anymore

### ISSUE THREAD

**Issue by drebolo** [plicease/NewRelic-Agent-FFI#5]
Following your link to [NewRelic Agent SDK](https://docs.newrelic.com/docs/agents/agent-sdk/getting-started/new-relic-agent-sdk) this is presented to us.
![Screenshot from 2020-01-09 13-13-35](https://user-images.githubusercontent.com/1061577/72070960-a5919280-32e2-11ea-842b-6b3a167b462f.png)

I still tried to use  NewRelic-Agent-FFI in my work but although the APP is created and available in the APPs list, nothing appears to be logged/reported to it.

Can you please confirm that is the case? Thank you.

**Comment by plicease** [comment]
As far as I can tell it is still working for our app.  Our app has been operating for a while, I suppose it is possible that NR isn't accepting data from new apps using this interface?  Do make sure that you are using the latest version: `nr_agent_sdk-v0.17.0.0-beta.x86_64.tar.gz`.  This is the version that `Alien::nragent` downloads by default if you are using that.  My plan was to write a new Perl wrapper for the new C SDK and migrate our app to that, though I haven't had the time to do that yet.

**Comment by drebolo** [comment]
Still unsuccessful to make it work, but it is really good to know about your future plans. :+1:

**Comment by drebolo** [comment]
I got it working now (a kind of, looks like running with --preload-app in starman app prevents it to work ) but can't get any added attribute `newrelic_transaction_add_attribute` visible in new relic, is this not working at all or could I be doing something wrong?

**Comment by plicease** [comment]
I know that bad things can and will happen if you try to use this module with `fork()` and do the `init` in the parent.

https://metacpan.org/pod/NewRelic::Agent::FFI#Not-Fork-Safe!
https://github.com/plicease/NewRelic-Agent-FFI/issues/2

So if you are using `--preload-app` or similar, you have to make sure that `init` isn't called in the parent.

From memory, I don't think we are using `newrelic_transaction_add_attribute` in our app, so I don't have any specific pointers on what might be going wrong, but this module only passes the values onto the newrelic code, I verified that the argument types match what is in the newrelic header files.

**Comment by plicease** [comment]
I've released 
https://metacpan.org/pod/NewFangle
which is bindings to the C-SDK.  I'm now marking this distribution as deprecated since it depends on software no longer supported by the its authors, and lacks source code.
